### ISSUE TITLE
Per-tag focus

### ISSUE THREAD

**Issue by thom-cameron** [alex-courtis/wideriver#16]
### Missing behavior

Not sure if this is possible to change in river, but when a view is assigned multiple tags, it steals focus when switching between those tags. 

For example:

- View foo is assigned tags 1 and 2
- View bar is assigned tag 1
- View baz is assigned tag 2

1. On tag 1, bar is focussed 
2. Switch to tag 2 and foo is automatically focussed
3. Manually change focus to baz
4. Switch back to tag 1 and foo is automatically focussed

### Desired solution

It would be nice if the tag layout retained the view that was originally focussed when you return to it. In the example, I'd like bar instead of foo to be automatically focussed when returning to tag 1.

Thanks and apologies if this isn't possible in river.

**Comment by alex-courtis** [comment]
That would be useful.

Unfortunately wideriver does not have control over focus.

It would be great if you could raise a river feature request at https://codeberg.org/river/river/issues or start a river IRC discussion: https://web.libera.chat/?channels=#river

**Comment by thom-cameron** [comment]
Ah, thanks and sorry about that then. I'll stick it on the river issue tracker instead.

**Comment by alex-courtis** [comment]
No need to apologise! The boundaries of responsibility are not very clear.
