### ISSUE TITLE
merged border when inner gaps=0

### ISSUE THREAD

**Issue by yugen-m7** [alex-courtis/wideriver#24]
### Missing behavior

when inner gaps are set to 0, there should be a single border between adjacent windows rather than each window having its own inner border

### Desired solution

something like [this](https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/minimalborders)

**Comment by alex-courtis** [comment]
That's a great idea. How would the CLI look? Perhaps:

```

  --border-width                  pixels                                2           0 <= width
  --border-width-monocle          pixels                                0           0 <= width
  --border-width-smart-gaps       pixels                                0           0 <= width

  --border-color-focused          0xRRGGBB[AA]                          0x93a1a1
  --border-color-focused-monocle  0xRRGGBB[AA]                          0x586e75
  --border-color-unfocused        0xRRGGBB[AA]                          0x586e75

  --border-merge

```

As usual, pull requests are most gratefully appreciated, see [CONTRIBUTING.md](https://github.com/nvim-tree/nvim-tree.lua/blob/master/CONTRIBUTING.md)

**Comment by yugen-m7** [comment]
I'll try but it will take a while since I'm completely new to this

**Comment by alex-courtis** [comment]
> I'll try but it will take a while since I'm completely new to this

No hurry.

A good starting point will be `arrange_master_stack`, where the view dimensions are set. It's got a dedicated unit test file `tst-arrange_master_stack.c`

**Comment by yugen-m7** [comment]
is there any resources or documentation that I can learn from??

**Comment by alex-courtis** [comment]
> is there any resources or documentation that I can learn from??

Take a look at https://github.com/alex-courtis/wideriver/blob/master/CONTRIBUTING.md

It starts with building and running tests.

Let me know if anything isn't clear; the doc can always be improved.
