### ISSUE TITLE
Gaps

### ISSUE THREAD

**Issue by phil-reyher** [alex-courtis/wideriver#4]
I'd love the option to add gaps between views.
Additionally, smart gaps would be awesome, similar to e.g. rivercarro, where gaps disappear for single views or the monocle layout.

Thanks you @alex-courtis for this amazing wm!

**Comment by alex-courtis** [comment]
Yes, we can definitely do that. It sounds like inner, outer and smart are necessary.

Please draft the necessary commands, as they would appear in `wideriver --help` or the man page. I'm not a gaps user so will likely miss something.

As usual, [Pull Requests](https://github.com/alex-courtis/wideriver/blob/master/CONTRIBUTING.md) are most gratefully appreciated.

**Comment by kyechou** [comment]
Hi @alex-courtis,

I've implemented the gaps in https://github.com/alex-courtis/wideriver/compare/master...kyechou:wideriver:master, which seems to be working fine on my setup, and all local tests are passing. However, I haven't gotten a chance to add new tests or update the documentation yet. I plan to send a PR after the tests and documentation are updated, but any feedback is welcomed in the meantime.

Thank you for creating the wm!
