### ISSUE TITLE
Border colour / width

### ISSUE THREAD

**Issue by Flapper01** [alex-courtis/wideriver#5]
I use tags in river like workspaces. I have tags 1 & 3 layout left, 2 and 4 are monocle.
The border colour (yellowish) and width (3) are shown on tag 1 but not on tag 3? Tag 3 appears to have no border at all.
Otherwise no problems, works great!

```
river -version
0.3.0-dev.293+b77b42f

```
Entire log:
```
I [16:59:53] --layout                       left
I [16:59:53] --layout-alt                   monocle
I [16:59:53] --stack                        dwindle
I [16:59:53] --count-master                 1
I [16:59:53] --ratio-master                 0.6
I [16:59:53] --count-wide-left              0
I [16:59:53] --ratio-wide                   0.35
I [16:59:53] --border-width                 3
I [16:59:53] --border-width-monocle         0
I [16:59:53] --border-color-focused         0x9ba03b
I [16:59:53] --border-color-focused-monocle 0x586e75
I [16:59:53] --border-color-unfocused       0x586e75
I [16:59:53] --log-threshold                info
I [16:59:53] wideriver started
```

and I switch between layouts as follows:
`riverctl map normal Super T     send-layout-cmd wideriver "--layout-toggle"`

**Comment by alex-courtis** [comment]
Your configuration looks correct. I'm able see the yellow borders on 3, however I'm clearly not replicating correctly:
* start river
* open a terminal on 1 - it has yellow borders
* switch to 3 with `set-focused-tags`
* open a terminal on 3 - it too has yellow borders

Perhaps you could make a recording of your session and note the actions you take.

[wf-recorder](https://github.com/ammen99/wf-recorder) works nicely, capturing the entire screen.

**Comment by alex-courtis** [comment]
FYI there is an issue which prevents the layout name from updating when you switch to an empty workspace. I'm constantly confused by that.

https://github.com/alex-courtis/wideriver?tab=readme-ov-file#name-does-not-always-update

**Comment by alex-courtis** [comment]
Great find, many thanks!

Added to quick start and faq:
https://github.com/alex-courtis/wideriver?tab=readme-ov-file#quick-start
https://github.com/alex-courtis/wideriver?tab=readme-ov-file#borders-are-not-shown

Closing this one, please reopen or comment if you have any further questions.
